# Generated by Django 5.0 on 2024-01-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255, verbose_name='property owner')),
                ('property_address', models.TextField()),
                ('property_location', models.CharField(max_length=255)),
                ('property_features', models.TextField()),
                ('rent_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedroom_type', models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK')], max_length=10)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstateHub.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('document_proofs', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pancard', 'PAN Card'), ('passport', 'Passport')], max_length=10)),
                ('document_image', models.FileField(null=True, upload_to='tenant_documents/')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstateHub.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_end_date', models.DateField()),
                ('monthly_rent_date', models.PositiveIntegerField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EstateHub.customuser')),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EstateHub.propertyunit')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EstateHub.tenant')),
            ],
        ),
    ]
