# Generated by Django 5.0 on 2024-01-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EstateHub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='propertyunit',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='admin_user',
        ),
    ]
